#!groovy

library identifier: '3scale-toolbox-jenkins@master',
        retriever: modernSCM([$class: 'GitSCMSource',
                              remote: 'https://github.com/rh-integration/3scale-toolbox-jenkins.git',
                              traits: [[$class: 'jenkins.plugins.git.traits.BranchDiscoveryTrait']]])

def service = null

node() {
  stage('Checkout Source') {
    checkout scm
  }

  stage("Prepare") {
          echo "Start of Prepare stage"
    service = toolbox.prepareThreescaleService(
        openapi: [filename: "saas-usecase-apikey/swagger.yaml"],
        environment: [ baseSystemName: "saas_usecase_apikey",
                       privateBaseUrl: "https://echo-api.3scale.net:443" ],
        toolbox: [ openshiftProject: "3scale-dev",
                   destination: "https://a48f4f726f8e454974de8ccdb91ea34fced3032803c5b17e20a0c4e6e1d6417c@3scale-admin.apps.ocpdev.snbdv.com/",
                   image: "quay.io/redhat/3scale-toolbox:master", // TODO: remove me once the final image is released
                   secretName: "3scale-toolbox"],
        service: [:],
        applications: [
            [ name: "my-test-app", description: "This is used for tests", plan: "test", account: "3" ]
        ],
        applicationPlans: [
          [ systemName: "test", name: "Test", defaultPlan: true, published: true ],
          [ systemName: "silver", name: "Silver" ],
          [ systemName: "gold", name: "Gold" ],
        ]
    )
       echo "END"
       echo "toolbox version = " + service.toolbox.getToolboxVersion()
  }

  stage("Import OpenAPI") {
    service.importOpenAPI()
    echo "Service with system_name ${service.environment.targetSystemName} created !"
  }

  stage("Create an Application Plan") {
    service.applyApplicationPlans()
  }

  stage("Create an Application") {
    service.applyApplication()
  }

  stage("Run integration tests") {
    // To run the integration tests when using APIcast SaaS instances, we need
    // to fetch the proxy definition to extract the staging public url
    def proxy = service.readProxy("sandbox")
    def userkey = service.applications[0].userkey
    sh """set -e
    echo "Public Staging Base URL is ${proxy.sandbox_endpoint}"
    echo "userkey is ${userkey}"
    curl -sfk -w "ListBeers: %{http_code}\n" -o /dev/null ${proxy.sandbox_endpoint}/api/beer -H 'api-key: ${userkey}'
    curl -sfk -w "GetBeer: %{http_code}\n" -o /dev/null ${proxy.sandbox_endpoint}/api/beer/Weissbier -H 'api-key: ${userkey}'
    curl -sfk -w "FindBeersByStatus: %{http_code}\n" -o /dev/null ${proxy.sandbox_endpoint}/api/beer/findByStatus/available -H 'api-key: ${userkey}'
    """
  }

  stage("Promote to production") {
    service.promoteToProduction()
  }

}
